#!/bin/sh
# vim: ft=sh ts=4 sw=4:

# Dirs
export APP_DIR="$HOME/Applications"
export BIN_DIR="$HOME/.local/bin"
export BACKUP_DIR="$HOME/Backups"
export NOTE_DIR="$HOME/Documents/Notes"
export SCHOOL_DIR="$HOME/Documents/School"
export PROGRAMMING_DIR="$HOME/Documents/Programming/Project"
export REPO_DIR="$HOME/Documents/Programming/Repo"

export BLOG="$HOME/Documents/Blog"
export DOTS="$HOME/.dotfiles"

export STARTPAGE_DIR="$HOME/.local/startpage"
export WALLPAPER_DIR="$HOME/.local/wallpaper"

# Misc
export WAL_BACKEND=colorthief       # wal colorthief

