#!/usr/bin/env bash
# shellcheck disable=SC2139

PERMISSION="${PERMISSION:-sudo}"       # sudo doas or any
EDITOR="${EDITOR:-nvim}"
TRASH_CMD=${TRASH_CMD:-gio}

# Find Alias
fa() { alias | grep "$1"; }

# Basic
# ----------------------
alias c="clear"
alias r="exec zsh"
alias :{q,Q}="exit"

# EDITOR Alias
# ----------------------
alias se="sudoedit"
alias {e,vi}="$EDITOR"
alias el="nvim -c 'lua  Util.session.last()'"
alias ep="nvim ~/.config/nvim/lua/plugins/init.lua"
alias {envim,ev}="$EDITOR ~/.config/nvim/init.*"

# Git Alias
# ----------------------
alias g="git"
alias ga="git add"
alias gr="git remove"
alias gs="git status"
alias glg="git log"
alias gb="git branch"
alias gco="git checkout"
alias gp="git push"
alias gl="git pull"
alias gf="git fetch"
alias gcm="git commit"
alias gcl="git clone --recursive"

alias {lg,lz}="lazygit"

# Better ls
# ----------------------
if command -v "exa" > /dev/null 2>&1; then
    alias ls="exa --icons --group-directories-first"
    alias lsa="exa --icons --group-directories-first -a"
    alias ll="exa --icons --group-directories-first -lgh"
    alias lla="exa --icons --group-directories-first -algh"
    alias {tree,lt}="exa --icons --group-directories-first -T"
fi

# Safety rm
# ----------------------
if [ "$TRASH_CMD" = "gio" ]; then
    alias rm="gio trash"
    alias trm="gio trash"
    alias trl="gio trash --list"
    alias trs="gio trash --restore"
elif [ "$TRASH_CMD" = "trash" ]; then
    alias rm="trash"
    alias trm="trash"
    alias trl="trash-list"
    alias trs="trash-restore"
fi

# tmux
# ----------------------
alias tma="tmux attach -t"
alias tmn="tmux new-session -s"
alias tmk="tmux kill-session -t"
alias tml="tmux list-sessions"
alias tms="tmux source-file ~/.config/tmux/tmux.conf"

# smug
# ----------------------
alias sm="smug"
alias sms="smug start"
alias smS="smug stop"
alias sme="smug edit"

# Kitty Terminal
# ----------------------
alias icat="kitty +kitten icat"

# neofetch
# ---------------------
alias kifetch="neofetch --config ~/.config/neofetch/config-kitty.conf"
alias fetch="neofetch --config none"

# mpd ncmpcpp
# ----------------------
alias mpd-kill="killall mpd ncmpcpp ncmpcpp_cover_art.sh"
alias mpd-album-art="~/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug"
alias mpd-restart="killmpd && mpd && mpdcpp"
alias mpd-lyrics="ncmpcpp --screen lyrics"

# Games
# ----------------------
if echo "$0" | grep "zsh" > /dev/null 2>&1; then
    alias tetris="autoload -Uz tetriscurses; tetriscurses"
fi

# cpupower
# ----------------------
alias performance="$PERMISSION cpupower frequency-set -g performance"
alias ondemand="$PERMISSION cpupower frequency-set -g ondemand"
alias cpuinfo="watch -n1 \"cat /proc/cpuinfo | grep 'MHz'\""

# Archlinux
# ----------------------
if cat /etc/*-release | grep "Arch"  > /dev/null 2>&1; then
    alias pacin="$PERMISSION pacman -S"
    alias pacsearch="pacman -Ss"
    alias pacupd="$PERMISSION pacman -Syy"
    alias pacupg="$PERMISSION pacman -Syu"
    alias pacrem="$PERMISSION pacman -Rns"
    alias pacrmorp="pacman Qtdq | $PERMISSION pacman -Rns -"

    pacsize(){
        LC_ALL=C pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h | grep "$1"
    }

    alias pain="paru -S"
    alias pasearch="paru -Ss"
    alias paupd="paru -Syy"
    alias paupg="paru -Syu"
    alias parem="paru -Rcns"
    alias parmorp="paru -Qtdq | paru -Rns -"
fi

# youtube-dl
# ----------------------
alias yt="youtube-dl"
alias yt720p="youtube-dl -f 'best[height<=720][ext=mp4]' --embed-thumbnail"
alias yt480p="youtube-dl -f 'best[height<=480][ext=mp4]' --embed-thumbnail"
alias ytm="youtube-dl --extract-audio --add-metadata --xattrs --embed-thumbnail --audio-quality 0 --audio-format mp3"

# Xresources Alias
# ----------------------
alias xload="xrdb -load ~/.Xresources"
alias xmerge="xrdb -merge ~/.Xresources"

# userscript
# ----------------------
alias tch="theme-changer"       # theme-changer
alias nt="note"                 # Note
