name: chat
parent: default

matches:
  # Salam
  - triggers: [":salamlengkap", ":salaml", ":lsalam"]
    replace: "Assalaamu'alaikum warahmatullaahi wabarakaatuh"

  - triggers: [":salamsingkat", ":salams", ":ssalam"]
    replace: "Assalaamu'alaikum"

  # Jawab Salam
  - triggers: [":jawablengkap", ":jawabl", ":ljawab"]
    replace: "Wa'alaikumus salam wa rahmatullahi wabarakatuh"

  - triggers: [":jawabsingkat", ":jawabs", ":sjawab"]
    replace: "Wa'alaikumussalam"

