name: indonesia
parent: default

matches:
  - trigger: "yg"
    replace: "yang"
    propagate_case: true

  - trigger: "dll"
    replace: "dan lain-lain"
    propagate_case: true

  - trigger: "dsb"
    replace: "dan lain sebagainya"
    propagate_case: true
