name: markdown
parent: default

matches:
  - trigger: ":md-c"
    replace: "```\n$|$\n```"

  - trigger: ":md-l"
    replace: "[$|$]({{clipboard}})"
    vars:
    - name: "clipboard"
      type: "clipboard"

  - trigger: ":md-i"
    replace: "![$|$]({{clipboard}})"
    vars:
    - name: "clipboard"
      type: "clipboard"

  - trigger: ":md-f"
    force_clipboard: true
    replace: |
      ---
      title: "$|$"
      author: "Atalariq Barra Hadinugraha"
      date: {{date}}
      ---
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":md-p"
    force_clipboard: true
    replace: |
      ---
      title: "$|$"
      author: "Atalariq Barra Hadinugraha"
      date: {{date}}
      extensions:
        - image_ueberzug
      ---
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

