name: url
parent: default

matches:
  ### Code
  - triggers: ["blog!", "myweb!"]
    replace: "https://atalazer.github.io"

  - triggers: ["github!", "gh!"]
    replace: "https://github.com"

  - triggers: ["gist!", "ghg!"]
    replace: "https://gist.github.com"

  - triggers: ["medium!", "md!"]
    replace: "https://medium.com"

  - triggers: ["devto!", "dt!"]
    replace: "https://dev.to"

  - triggers: ["hackernoon!", "hn!"]
    replace: "https://hackernoon.com"

  ### Social Media
  - triggers: ["facebook!", "fb!"]
    replace: "https://facebook.com"

  - triggers: ["instagram!", "ig!"]
    replace: "https://instagram.com"

  - triggers: ["twitter!", "tw!"]
    replace: "https://twitter.com"

  - triggers: ["reddit!", "rd!"]
    replace: "https://reddit.com"

  - triggers: [":uru", "runixporn!", "rup!"]
    replace: "https://reddit.com/r/unixporn"

  - triggers: [":urn", "rneovim!", "rnvim!", "rnv!"]
    replace: "https://reddit.com/r/neovim"

  - triggers: ["idquora!", "idq!"]
    replace: "https://id.quora.com"
  
  ### Others
  - triggers: ["whatsapp!", "wa!"]
    replace: "https://web.whatsapp.com/"

  - triggers: ["telegram!", "tg!"]
    replace: "https://web.telegram.org"

  - triggers: ["elearning!", "el!"]
    replace: "https://e.smpn1boyolali.sch.id/"

