format = """$all"""
# right_format = """$all"""

[directory]
truncation_length = 8

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[package]
disabled = true

[golang]
format = "via [ $version](bold blue) "

[lua]
format = "via [ $version](bold blue) "

