#!/bin/sh
# vim: ft=sh ts=4 sw=4:

delta=5
lock_timeout=600
suspend=${SUSPEND_CMD:-"systemctl suspend"}
brightness_up="brightnessctl -d $delta up"
brightness_down="brightnessctl -d $delta down"
notify="notify-send 'Lockscreen' 'Screen Will Be Lock After 5 Sec'"
# Set Lock Command Based On WM
if [ -n "$CHECK_AWESOME_CLIENT" ]; then WM="AWESOME"; else WM="NOT_AWESOME"; fi
case $WM in
    AWESOME) lock="awesome-client 'lock_screen_show()'" ;;
    NOT_AWESOME) lock="slock" ;;
    *) lock="" ;;
esac

# Run xidlehook
[ -n "$(pgrep xidlehook)" ] && pkill xidlehook && killall xidlehook
xidlehook \
    --not-when-fullscreen \
    --not-when-audio \
    --timer $((lock_timeout / 2)) \
    "$brightness_down" \
    "$brightness_up" \
    --timer $((lock_timeout - 5)) \
    "$notify" \
    "$brightness_up" \
    --timer $((lock_timeout)) \
    "$brightness_up && $lock" \
    "$brightness_up" \
    --timer $((lock_timeout + 300)) \
    "$suspend" \
    "$brightness_up"
