#!/bin/sh

player_state_file="$HOME/.cache/music-player"
[ ! -f "$player_state_file" ] && echo "mpd" > "$player_state_file"

player="$(cat "$player_state_file")"

player_list="mpd mpv spotify"

pick(){
   player="$(echo "$player_list" | tr " " "\n" )"
   picker=$(printf "mpd\nmpv\nspotify" | rofi -dmenu )
   echo "$picker" > "$player_state_file"
   echo "Set current player to $picker"
}

if [ "$player" = "mpd" ]; then
    command -v "mpc" >/dev/null 2>&1 || echo "Please Install mpc first"
    prev="mpc -q prev"
    toggle="mpc -q toggle"
    stop="mpc -q stop"
    next="mpc -q next"
    status="mpc status"
    title="$(mpc --format '[%title%|%file%]' current)"
elif [ "$player" = "mpv" ]; then
    command -v "mpvc" >/dev/null 2>&1 || echo "Spotify not installed"
    prev="mpvc --toggle"
    next="mpvc --toggle"
    stop="mpvc --stop"
    toggle="mpvc --toggle"
    status="mpvc"
    title="MPV"
elif [ "$player" = "spotify" ]; then
    command -v "spotify" >/dev/null 2>&1 || echo "Spotify not installed"
    prev="playerctl -p spotify previous"
    next="playerctl -p spotify next"
    stop="playerctl -p spotify stop"
    toggle="playerctl -p spotify play-pause"
    status="playerctl -p spotify status"
    title="$(playerctl -p spotify metadata -f '{{title}}')"
else
    prev="" toggle="" stop="" next="" status=""
    title="There's no available player!"
fi

status="$($status)"

help() {
    cat <<EOF
Usage for $(basename "$0"):
  Command:
    next          Play next
    prev          Play previous
    status        Show status
    stop          Stop music
    toggle        Toggle music
    titile        Show title
    pick          Pick player
  Options
    -h, --help      Show this message
    -p, --player    Change music player (default: mpd, available: $player_list)
EOF
}

while [ -n "$1" ]; do
    case "$1" in
    toggle) sh -c "$toggle" ;;
    stop) sh -c "$stop" ;;
    next) sh -c "$next" ;;
    prev) sh -c "$prev" ;;
    status) echo "$status" ;;
    title) echo "$title" ;;
    pick) pick ;;
    "-p" | "--player")
        shift
        [ -n "$1" ] && player="$1"
        ;;
    "-h" | "--help") help ;;
    *) echo "Invalid" && help ;;
    esac
    shift
done
