zstyle :plugin:fast-syntax-highlighting theme "atalazer"
typeset -g FAST_THEME_NAME="atalazer"
: ${FAST_HIGHLIGHT_STYLES[atalazerdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[atalazerunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerreserved-word]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazeralias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazersuffix-alias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerbuiltin]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerfunction]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazercommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerprecommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazercommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[atalazerhashed-command]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerpath]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[atalazerpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[atalazerglobbing]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerglobbing-ext]:=fg=13}
: ${FAST_HIGHLIGHT_STYLES[atalazerhistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazersingle-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[atalazerdouble-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[atalazerback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[atalazersingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazerdouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazerdollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazerback-or-dollar-double-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[atalazerback-dollar-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[atalazerassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[atalazerredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[atalazercomment]:=fg=243}
: ${FAST_HIGHLIGHT_STYLES[atalazervariable]:=fg=113}
: ${FAST_HIGHLIGHT_STYLES[atalazermathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazermathnum]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[atalazermatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[atalazerassign-array-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[atalazerfor-loop-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[atalazerfor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazerfor-loop-separator]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerhere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazerhere-string-text]:=fg=18}
: ${FAST_HIGHLIGHT_STYLES[atalazerhere-string-var]:=fg=cyan,bg=18}
: ${FAST_HIGHLIGHT_STYLES[atalazersecondary]:=free}
: ${FAST_HIGHLIGHT_STYLES[atalazercase-input]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazercase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazercase-condition]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[atalazercorrect-subtle]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[atalazerincorrect-subtle]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[atalazersubtle-separator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazersubtle-bg]:=bg=18}
: ${FAST_HIGHLIGHT_STYLES[atalazerpath-to-dir]:=fg=magenta,underline}
: ${FAST_HIGHLIGHT_STYLES[atalazerpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[atalazerbracket-level-1]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerbracket-level-2]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerbracket-level-3]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[atalazerglobal-alias]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[atalazersubcommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazersingle-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerdouble-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[atalazerdouble-paren]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazeroptarg-string]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[atalazeroptarg-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[atalazerrecursive-base]:=none}
