#!/bin/sh
# vim: ft=sh ts=4 sw=4:

schedule() {
    SCHEDULE=${SCHEDULE:-$HOME/Documents/Notes/schedule.md}
    if [ ! -f "$SCHEDULE" ]; then
        touch "$SCHEDULE"
        echo "$SCHEDULE Created"
    else
        OPT=${1:---help}
        case $OPT in
        "-e" | "--edit") "${EDITOR:-nvim}" "$SCHEDULE" ;;
        "-s" | "--show")
            if command -v "glow" >/dev/null 2>&1; then
                glow -p "$SCHEDULE"
            elif command -v "bat" >/dev/null 2>&1; then
                bat --paging=always "$SCHEDULE"
            else
                cat "$SCHEDULE"
            fi
            ;;
        "-h" | "--help")
            echo "Command:"
            echo "-e --edit Edit SCHEDULE file"
            echo "-s --show Show SCHEDULE"
            echo "-h --help Show available command"
            ;;
        esac
    fi
}
alias sc="schedule"
alias scs="schedule -s"
alias sce="schedule -e"
