# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

auto_restart: true
undo_backspace: true
fast_inject: false

enable_active: true
enable_passive: true
passive_key: CTRL
toggle_key: RIGHT_ALT

show_icon: true
show_notifications: true

matches:
  # Globals
  - triggers: [":name", ":nama"]
    replace: "Atalariq Barra Hadinugraha"
    propagate_case: true

  - triggers: [":user", ":pengguna"]
    replace: "atalazer"
    propagate_case: true

  - triggers: [":email1", ":mail1"]
    replace: "baraboyolali@gmail.com"
  
  - triggers: [":email2",":mail2"]
    replace: "atalariq26@gmail.com"
  
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"

  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: "::date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%A, %d %B %Y"

  # Outputs the current time (24hr)
  - trigger: ":time"
    replace: "{{time}}"
    vars:
    - name: time
      type: date
      params:
        format: "%H:%M"

