#!/bin/sh

if command -v "doas" &> /dev/null; then
    PERMISSION="doas"
else
    PERMISSION="sudo"
fi

# Arch-based
if command -v "pacman" &> /dev/null; then
    if command -v "paru" &> /dev/null; then
        AUR_HELPER="paru"
    elif command -v "yay" &> /dev/null; then
        AUR_HELPER="yay"
    elif command -v "trizen" &> /dev/null; then
        AUR_HELPER="trizen"
    else
        echo "Please install AUR helper like paru or yay"
        exit 0
    fi

    echo "===================================================="
    echo "Update All Packages"
    echo "===================================================="

    $PERMISSION pacman -Syu --noconfirm

    echo "===================================================="
    echo "Installing dependencies"
    echo "===================================================="
    $PERMISSION pacman -S --noconfirm stow

    echo "1) xf86-video-intel 	2) xf86-video-amdgpu 3) Skip"
    read -r -p "Choose you video card driver(default 1)(will not re-install): " vid

    case $vid in 
        [1]) DRI='xf86-video-intel';;
        [2]) DRI='xf86-video-amdgpu';;
        [3]) DRI="";;
        [*]) DRI='xf86-video-intel';;
    esac

    echo "===================================================="
    echo "Installing Package for $(lsb_release -d | cut -f 2)"
    echo "===================================================="

    $AUR_HELPER -S --needed --noconfirm \
        xorg xorg-server \
        xorg-xinit xorg-xprop xorg-xrdb \
        xcb-util-errors \
        xf86-input-libinput $DRI \
        xsettingsd \
        xdg-user-dirs \
        thunar thunar-archive-plugin thunar-volman \
        maim xdotool feh inotify-tools \
        rofi clipmenu \
        kitty alacritty zsh tmux \
        python-pywal python-colorthief \
        htop neofetch ueberzug w3m \
        pulseaudio playerctl pamixer \
        mpd mpc ncmpcpp \
        lm_sensors acpid jq fortune-mod redshift \
        awesome-git picom-jonaburg-git light-git \
        ruby-fusuma ruby-fusuma-plugin-keypress ruby-fusuma-plugin-wmctrl \
        ruby-fusuma-plugin-sendkeys ruby-fusuma-appmatcher

    read -r -p "Do you want to install neovim stuff(lsp and formatter) [yes/no]: " NVIM

    case $NVIM in
        [yY][eE][sS]|[yY])
            echo "===================================================="
            echo "Install nvim stuff packages"
            echo "===================================================="

            echo "Install Package with $AUR_HELPER"
            $AUR_HELPER -S --noconfirm \
                neovim \
                python \
                python-pip \
                lua-language-server \
                jedi-language-server \
                clang \
                stylua-bin \
                python-black \
                shfmt

            echo "Install Package with npm"
            if command -v "npm" &> /dev/null; then
                npm install -g \
                    neovim \
                    vscode-langservers-extracted \
                    bash-language-server \
                    vim-language-server \
                    yaml-language-server \
                    prettier
            else
                echo "Please Install npm first"
            fi
            
            echo "Install other stuff"
            if command -v "pip" &> /dev/null; then
                pip install --upgrade pynvim
            fi

            ;;
        [nN][oO]|[nN]) exit 0 ;;
        [*]) exit 0 ;;
    esac

    echo "===================================================="
    echo "Done; Package Installed"
    echo "===================================================="
fi

