#!/usr/bin/env bash

OPT="${1:-"help"}"

case $OPT in
  build)
    CFG=${2:-"linux"}
    echo "Build for $CFG configuration"

    # Install nix if not installed
    [ ! -f $(which nix-shell) ] && curl -L https://nixos.org/nix/install | sh

    # Build
    nix-shell -p nixUnstable --command "nix build --experimental-features 'nix-command flakes' '.#$CFG'" \
      && echo "Build succes!"
    ;;
  apply)
    [ -f result/activate ] && result/activate
    stow -d configs -t $HOME -D home
    ;;
  help|*)
    echo "Usage:"
    echo "help      Show this message."
    echo "build     Build configuration. (default: linux)"
    echo "apply     Activate existing configuration."
  ;;
esac

# vim:set ft=bash sw=2 ts=2:
