#!/usr/bin/env bash

OPT="${1:-"help"}"

case $OPT in
  build)
    # Install nix if not installed
    [ ! $(command -v "nix-shell" > /dev/null 2>&1) ] && curl -L https://nixos.org/nix/install | sh

    # Build
    nix-shell -p nixUnstable --command "nix build --experimental-features 'nix-command flakes' '.#$CFG'" && echo "Build succes!"
    ;;
  linux)
    [ -f result/activate ] && result/activate
    stow -d configs -t $HOME -R all
    stow -d configs -t $HOME -R linux
    ;;
  termux)
    stow -d configs -t $HOME -R all
    stow -d configs -t $HOME -R termux
    ;;
  help|*)
    echo "Usage:"
    echo "help      Show this message."
		echo "build     Build configuration with Nix (Only for Linux)"
    echo "linux     Apply config for linux"
    echo "termux    Apply config for termux"
  ;;
esac

# vim:set ft=bash sw=2 ts=2:
