#!/bin/sh

if command -v "pet" > /dev/null 2>&1; then return; fi

# Register the previous command easily
prev() {
    PREV=$(fc -lrn | head -n 1)
    sh -c "pet new $(printf %q "$PREV")"
}

# Select snippets at the current line (like C-r)
pet-select() {
    BUFFER=$(pet search --query "$LBUFFER")
    CURSOR=$#BUFFER
    zle redisplay
}

zle -N pet-select
stty -ixon
bindkey '^s' pet-select
