#!/usr/bin/env bash

# clone subdirectory using subversion
git-svn() {
    if [ -n "$1" ] && [ -n "$2" ]; then
        echo "Starting clone/copy..."
        repo=$(echo "$1" | sed 's/\/$\|.git$//')
        svn export "$repo/trunk/$2"
    else
        echo "Use: git-svn <repository> <subdir>"
    fi
}
