#!/usr/bin/env bash
# vim: ft=sh:

dict(){
    DIR=$HOME/Documents/Dictionary
    FILE=$DIR/$(date '+%Y-%m-%d').md
    if [ ! -d "$DIR" ]; then mkdir -p "$DIR"; fi
    if [ ! -f "$FILE" ]; then 
        echo "|Word|Meaning|\n|---|---|" > "$FILE"
    fi

    OPT=${1:-show}
    case $OPT in
        "-a"|"--add")
            WORD="$2"
            MEAN="$3"
            if [ -z "$WORD" ]; then exit 1; fi
            if [ -z "$MEAN" ]; then exit 1; fi

            echo "|$WORD |$MEAN|" >> "$FILE"
            nvim --headless -c "TableModeRealign" "$FILE" -c "wq" >/dev/null 2>&1
            ;;
        "-s"|"--show")
            if command -v "glow" > /dev/null 2>&1; then
                glow "$FILE"
            else
                cat "$FILE"
            fi
            ;;
        "-e"|"--edit") ${EDITOR:-nvim} "$FILE";;
        *)  echo "Invalid Argument" ;;
    esac
}
alias dca="dict --add"
alias dcs="dict --show"

