#!/bin/sh

find_note() {
    dir=$HOME/Documents/Notes
    while [ -n "$1" ]; do
        case "$1" in
        "-d" | "--dir")
            shift
            dir="$1"
            ;;
        esac
        shift
    done

    file="$(fd . "$dir" -e md --type file --color never | sed -e "s#${dir}/##" -e "s#.md##" |
            fzf --bind 'J:preview-down,K:preview-up' --height 100% \
                --preview "glow -s dark $dir/{}.md"
    )"

    if [ -n "$file" ]; then
        nvim "$dir"/"$file".md
    fi
    unset dir; unset file
}

notes() {
    while [ -n "$1" ]; do
        case "$1" in
        "-f" | "--find") find_note "$@";;
        esac
        shift
    done
}
