#!/bin/sh

# Alias Finder
fa() {
    alias | grep "$1"
}

stats() {
    fc -l 1 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | \
        grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n20
}

take() {
    if command -v "zoxide" > /dev/null 2>&1; then CD="z"; else CD="cd"; fi
    mkdir -p $@ && $CD ${@:$#}
}

