column_width = 120
line_endings = "Unix"                           # Unix(LF) or Windows(CRLF)
indent_type = "Tabs"                            # Tabs or Spaces
indent_width = 4
quote_style = "AutoPreferDouble"                # AutoPreferDouble AutoPreferSingle ForceDouble ForceSingle
