gui:
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.4
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

git:
  paging:
    colorArg: always
    useConfig: false
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"

os:
  openCommand: 'sh -c "xdg-open {{filename}} >/dev/null"'

notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
