session: school
root: ~/Documents/School

windows:
- name: Notes
  commands: 
    - clear
- name: Schedule
  commands: 
    - SCHEDULE=~/Documents/School/jadwal.md schedule --show
- name: Others
  commands: 
    - clear
