# Generate by wal
colors:
  # Default colors
  primary:
    background: "{background}"
    foreground: "{foreground}"

  cursor:
    text: CellBackground
    cursor: "{cursor}"

  vi_mode_cursor:
    text: CellBackground
    cursor: "{cursor}"

  line_indicator:
    foreground: None
    background: None

  selection:
    text: CellBackground
    background: CellForeground

  # Normal colors
  normal:
    black:   "{color0}"
    red:     "{color1}"
    green:   "{color2}"
    yellow:  "{color3}"
    blue:    "{color4}"
    magenta: "{color5}"
    cyan:    "{color6}"
    white:   "{color7}"

  # Bright colors
  bright:
    black:   "{color8}"
    red:     "{color9}"
    green:   "{color10}"
    yellow:  "{color11}"
    blue:    "{color12}"
    magenta: "{color13}"
    cyan:    "{color14}"
    white:   "{color15}"
