#!/bin/sh
# shellcheck disable=SC2034

# Shell variables
# Generated by "wal"
wallpaper="{wallpaper}"

# Special
background="{background}"
foreground="{foreground}"
cursor="{cursor}"

# Colors
color0="{color0}"
color1="{color1}"
color2="{color2}"
color3="{color3}"
color4="{color4}"
color5="{color5}"
color6="{color6}"
color7="{color7}"
color8="{color8}"
color9="{color9}"
color10="{color10}"
color11="{color11}"
color12="{color12}"
color13="{color13}"
color14="{color14}"
color15="{color15}"

black=$color0
red=$color1
green=$color2
yellow=$color3
blue=$color4
magenta=$color5
cyan=$color6
white=$color7
light_black=$color8
light_red=$color9
light_green=$color10
light_yellow=$color11
light_blue=$color12
light_magenta=$color13
light_cyan=$color14
light_white=$color15
