format = "$all"
scan_timeout = 100
command_timeout = 1000

[directory]
truncation_length = 8

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[shell]
fish_indicator = ""
zsh_indicator = "_"
disabled = false

