#!/usr/bin/env bash
up="light -A 2"
down="light -U 2"

current_bn() {
    light -G | cut -c 1-2
}

optimize (){
    light -S 10
    if [ ! -z $(pgrep redshift) ];
    then
        redshift -x && pkill redshift && killall redshift
        echo 'OFF'
    else
        redshift -l 0:0 -t 4500:4500 -r &>/dev/null &
        echo 'ON'
    fi
}

case $1 in
    up)
        bash -c "$up"
        # notify-send $(current_bn)
    ;;
    down)
        bash -c "$down"
        # notify-send $(current_bn)
    ;;
    optimize)
        optimize
    ;;
esac
