#!/usr/bin/env bash

# Author:  Atalazer (baraboyolali@gmail.com)
# License: MIT
# Depends: light, redshift, gammastep

TIME=$(date "+%H")
BRIGHTNESS="15"
TEMPERATURE="4000:4000"

auto() {
    if [[ $TIME -ge 15 || $TIME -le 5 ]]; then
        light -S $BRIGHTNESS
        if [ $XDG_SESSION_TYPE == "wayland" ]; then
            if [[ -z $(pgrep gammastep) ]]; then
                gammastep -l 0:0 -t $TEMPERATURE -r &>/dev/null &
                echo "ON"
            fi
        else
            if [[ -z $(pgrep redshift) ]]; then
                redshift -l 0:0 -t $TEMPERATURE -r &>/dev/null &
                echo "ON"
            fi
        fi
    else
        light -S 30
        if [ $XDG_SESSION_TYPE == "wayland" ]; then
            if [[ ! -z $(pgrep gammastep) ]]; then
                gammastep -x && pkill redshift && killall redshift
                echo "OFF"
            fi
        else
            if [[ ! -z $(pgrep redshift) ]]; then
                redshift -x && pkill redshift && killall redshift
                echo "OFF"
            fi
        fi
    fi
}
on() {
    light -S $BRIGHTNESS
    if [ $XDG_SESSION_TYPE == "wayland" ]; then
        if [[ -z $(pgrep gammastep) ]]; then
            gammastep -l 0:0 -t $TEMPERATURE -r &>/dev/null &
            echo "ON"
        fi
    else
        if [[ -z $(pgrep redshift) ]]; then
            redshift -l 0:0 -t $TEMPERATURE -r &>/dev/null &
            echo "ON"
        fi
    fi
}

off() {
    light -S 30
    if [ $XDG_SESSION_TYPE == "wayland" ]; then
        if [[ ! -z $(pgrep gammastep) ]]; then
            gammastep -x && pkill redshift && killall redshift
            echo "OFF"
        fi
    else
        if [[ ! -z $(pgrep redshift) ]]; then
            redshift -x && pkill redshift && killall redshift
            echo "OFF"
        fi
    fi
}

OPT=${1:-help}
case $OPT in
    help)
        echo "Usage:"
        echo "auto      Automatticaly run based on time"
        echo "on        Force run"
        echo "off       Force Stop"
        ;;
    auto) auto ;;
    on) on ;;
    off) off ;;
esac
