#!/usr/bin/env bash

editor=${VISUAL:-vim}
_TERMINAL="$_TERMINAL"  # same goes for the terminal

if [ -e "${TMUX%%,*}" ] && tmux -V | grep -q '[ -][3456789]\.'; then
    _TERMINAL=tmux
elif [ -n "$KITTY_WINDOW_ID" ] && kitty @ ls >/dev/null 2>&1; then
    _TERMINAL=kitty
else
    _TERMINAL="${_TERMINAL:-xterm}"
fi

if [ "$_TERMINAL" = "tmux" ]; then
    tmux split-window -h "$editor \"$*\""
elif [ "$_TERMINAL" = "kitty" ]; then
    kitty @ goto-layout splits >/dev/null
    kitty @ launch --no-response --title "nnn editor" --keep-focus \
          --cwd "$PWD" --env "PATH=$PATH" --env "NNN_FIFO=$NNN_FIFO" \
          --location "vsplit" $editor "$*"
else
    $editor "$*"
fi
