#!/usr/bin/env bash

# Toggle visualizer:
# Kill it if it is running or spawn it if it does not running
xdotool search --name Visualizer &>/dev/null && \
    (ps x | grep "kitty --name Visualizer" | grep -v grep | awk '{print $1}' | xargs kill) || \
    kitty --class Visualizer -o background_opacity=0 -o font_size=6 -o window_margin_width=0 -e cava &

