[[snippets]]
  description = "espanso: Restart"
  command = "espanso restart"
  output = ""

[[snippets]]
  description = "fzf+glow: Glow as FZF Preview"
  command = "fzf --reverse --height 100% --preview \"glow -s dark {}\""
  output = ""

[[snippets]]
  description = "fzf+glow: Pick Markdown File, then Open It With Glow."
  command = "glow \"$(fzf --reverse --preview 'bat --style=numbers --color=always {}')\""
  output = ""

[[snippets]]
  description = "gpg: Reload GPG Agent"
  command = "gpg-connect-agent reloadagent /bye"
  output = ""

[[snippets]]
  description = "pandoc: Convert md to pdf"
  command = "pandoc --pdf-engine=pdflatex FILE.md -o FILE.pdf"
  output = ""

[[snippets]]
  description = "rofi: Calc"
  command = "rofi -show calc -modi calc -no-show-match -no-sort"
  output = ""

[[snippets]]
  description = "script: School Schedule"
  command = "source ~/.config/shell/functions/schedule && SCHEDULE=~/Documents/School/jadwal.md schedule --show"
  output = ""

[[snippets]]
  description = "smug+tmux: Start Session For School"
  command = "smug start school"
  output = ""
