#!/bin/sh

DMENU="rofi -dmenu -i"
_XDG_=$(xdg-user-dir VIDEOS)
DIR="${_XDG_:-$HOME/Videos}"

if command -v "mpvc" >/dev/null 2>&1; then true; else exit 1; fi

OPT=${1:-find}
case $OPT in
track | "-t")
    track=$(mpvc -i | sed -r 's/\x1B\[(;?[0-9]{1,3})+[mGK]//g' | tr -d "\t" | $DMENU -p "MPV Track" | cut -d " " -f 1)
    [ -n "$track" ] && mpvc -J "$track"
    ;;
playlist | "-p")
    PLAYLIST_DIR=$HOME/.config/mpv/playlist
    PLAYLIST_FILE=$(find "$PLAYLIST_DIR" | $DMENU -p "MPV Playlist" -l 10)

    [ -n "$PLAYLIST_FILE" ] && mpv "${PLAYLIST_DIR}/${PLAYLIST_FILE}"
    ;;
find | "-f")
    filename=$(find "$DIR" -type f -regex '.*.\(mp4\|mkv\)' | \
        sed s/"\/home\/atalariq\/Videos\/"// | \
        rofi -dmenu -p "Videos" -width 70 -lines 20 \
            -case-sensitive \
    )
    video="$DIR/$filename"
    [ -f "$video" ] && mpv "$video"
    ;;
esac
