#!/usr/bin/env bash

export FORGIT_FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS
FORGIT_PAGER=$PAGER
FORGIT_SHOW_PAGER=$FORGIT_PAGER
FORGIT_DIFF_PAGER="$(git config pager.diff || echo 'delta --diff-so-fancy --line-numbers')"
FORGIT_IGNORE_PAGER="bat -l gitignore --color always"

export forgit_log=glg
export forgit_diff=gd
export forgit_add=ga
export forgit_reset_head=grh
export forgit_ignore=gi
export forgit_checkout_file=gcf
export forgit_checkout_branch=gcb
export forgit_checkout_commit=gco
export forgit_clean=gclean
export forgit_stash_show=gss
export forgit_cherry_pick=gcp
export forgit_rebase=grb
export forgit_fixup=gfu
