#!/bin/sh

export FZF_DEFAULT_COMMAND="rg --files --no-ignore --ignore-file '.gitignore'"
export FZF_DEFAULT_OPTS="
    --height 70%
    --layout=reverse
    --border
    --preview-window=right:60%
"
export FZF_PREVIEW="bat --style=numbers --color=always {}"

alias fzfp="fzf --reverse --preview '$FZF_PREVIEW'"

