#!/usr/bin/env bash

if command -v "sk" >/dev/null 2>&1; then
    export SKIM_DEFAULT_COMMAND=$FZF_DEFAULT_COMMAND
    export SKIM_DEFAULT_OPTS=$FZF_DEFAULT_OPTS
    export SKIM_PREVIEW=$FZF_PREVIEW

    alias skp="sk --reverse --preview '$SKIM_PREVIEW'"
fi
