[[snippets]]
  description = "espanso: Restart"
  command = "espanso restart"
  output = ""

[[snippets]]
  description = "fzf+glow: Glow as FZF Preview"
  command = "fzf --reverse --height 100% --preview \"glow -s dark {}\""
  output = ""

[[snippets]]
  description = "fzf+glow: Pick Markdown File, then Open It With Glow."
  command = "glow \"$(fzf --reverse --preview 'bat --style=numbers --color=always {}')\""
  output = ""

[[snippets]]
  description = "gpg: Reload GPG Agent"
  command = "gpg-connect-agent reloadagent /bye"
  output = ""

[[snippets]]
  description = "pandoc: Convert md to pdf"
  command = "pandoc --pdf-engine=pdflatex FILE.md -o FILE.pdf"
  output = ""

[[snippets]]
  description = "rofi: Calc"
  command = "rofi -show calc -modi calc -no-show-match -no-sort"
  output = ""

[[snippets]]
  description = "script: School Schedule"
  command = "source ~/.config/shell/functions/schedule && SCHEDULE=~/Documents/School/jadwal.md schedule --show"
  output = ""

[[snippets]]
  description = "smug+tmux: Start Session For School"
  command = "smug start school"
  output = ""

[[snippets]]
  description = "tmux: Reload Config"
  command = "tmux source-file ~/.config/tmux/tmux.conf"
  output = ""

[[snippets]]
  description = "gpg: Show secret key list"
  command = "gpg --list-secret-keys --keyid-format=long"
  output = ""

[[snippets]]
  description = "syncthing: Start daemon"
  command = "syncthing -no-browser -no-restart -logflags=0 -logfile=$HOME/.cache/syncthing"
  output = ""

[[snippets]]
  description = "ip: Get local IP Address"
  command = "ip addr show wlan0 | grep inet | awk '{print $2}' | head -n 1 | sed -e 's#/24##'"
  output = ""

[[snippets]]
  description = "browser-sync: Start server across local network(LAN)"
  command = "SERVER_IP=$(ip addr show wlan0 | grep inet | awk '{print $2}' | head -n 1 | sed -e 's#/24##'); browser-sync start --server --files . --no-notify --host $SERVER_IP --port 9000"
  output = ""

[[snippets]]
  description = "surf: Open Osu!Lazer Releases Page to Update"
  command = "surf https://github.com/ppy/osu/releases"
  output = ""

[[snippets]]
  description = "ss: Show open port"
  command = "sudo ss -tulpn"
  output = ""
