# NOTE SETTINGS
[note]
# language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 6
id-case = "lower"
ignore = []

# EXTRA VARIABLES
[extra]
visibility = "public"
author = "Atalariq Barra Hadinugraha"

# GROUP OVERRIDES
[group.diary_journal]
path = [ "diary/*", "journal/*" ]

[group.diary_journal.note]
filename = '{{date now "%Y%m%d"}}'

[group.school]
path = ["School/*", "school/*"]

[group.school.note]
filename = '{{date now "%Y%m%d"}}-{{slug title}}'
extension = "md"
template = "school.md"

# MARKDOWN SETTINGS
[format.markdown]
link-format = "wiki"
link-encode-path = false
link-drop-extension = true

hashtags = true
colon-tags = false
multiword-tags = false

# EXTERNAL TOOLS
[tool]
editor = "nvim"
pager = "less -R"
fzf-preview = "bat -p --color always {-1}"

# LSP
[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[filter]
recents = "--sort created- --created-after 'last two weeks'"
journal = "--sort created journal"

# COMMAND ALIASES
[alias]
last = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
l = "zk list $@"
e = "zk edit $@"
n = "zk new $@"
edit = "zk edit --interactive $@"
