#!/bin/sh

[ -f "${XDG_CACHE_HOME:-$HOME/.cache/wal}/colors.sh" ] && . "${XDG_CACHE_HOME:-$HOME/.cache/wal}/colors.sh"

green=${green:-#5fff87}
yellow=${yellow:-#ffaf5f}
blue=${blue:-#af87ff}
magenta=${magenta:-#ff87d7}
export FZF_TMUX=1

if command -v "fd" > /dev/null 2>&1; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
else
    export FZF_DEFAULT_COMMAND="rg --files --no-ignore --ignore-file '.gitignore'"
fi

DRACULA="
--color=dark
--color=fg:-1,bg:-1,hl:$green,fg+:-1,bg+:-1,hl+:$yellow
--color=info:$blue,prompt:$green,pointer:$magenta,marker:$magenta,spinner:$magenta
"

export FZF_DEFAULT_OPTS="
--cycle
--exact
--reverse
--layout=reverse
--height '70%'
--preview-window=right:60% 
--prompt='|> '
--pointer='❯'
--marker='*'
--bind 'pgup:preview-page-up,pgdn:preview-page-down'
--bind 'J:preview-down,K:preview-up'
--bind 'alt-j:down,alt-k:up'
$DRACULA
"

export FZF_PREVIEW="bat --style=numbers --color=always --line-range :500 {}"

# Aliases
alias fzfp="fzf --reverse --preview '$FZF_PREVIEW'"

