#!/usr/bin/env bash
current_musicpl=$(cat ~/.cache/music-mode)

user_music_notify=yes

if [ $user_music_notify = "yes" ]; then
    notify="~/.local/script/music-notify.sh"
else
    notify=""
fi

if [[ $current_musicpl = "mpd" ]]; then
    prev="mpc -q prev"
    toggle="mpc -q toggle"
    stop="mpc -q stop"
    next="mpc -q next"
    status="mpc status"
    title="$(mpc --format '[%title%|%file%]' current)"
else
    if [[ $current_musicpl = "nompd" ]]; then
        prev="playerctl -p previous"
        toggle="playerctl -p play-pause"
        stop="playerctl -p stop"
        next="playerctl -p next"
        status="playerctl -p status"
        title="$(playerctl -p metadata -f '{{title}}')"
    else
        prev=""
        toggle=""
        stop=""
        next=""
        status=""
        title="There is no mpd installed"
    fi
fi
status="$($status)"

case $1 in
    current)
        bash -c "$notify"
    ;;
    toggle) 
        bash -c "$toggle"
    ;;
    stop) 
        bash -c "$stop"
    ;;
    next) 
        bash -c "$next"
        bash -c "$notify"
    ;;
    prev) 
        bash -c "$prev"
        bash -c "$notify"
    ;;
    icon)
        if [[ $status = *"laying"* ]]; then
            echo ""
        else
            echo ""
        fi
    ;;
    status) echo "$status"
    ;;
    title) echo "$title"
    ;;
    switchpl)
        [[ $status = *"laying"* ]] && bash -c "$toggle"
        if [[ $current_musicpl = "mpd" ]]; then
            echo "nompd" > $current_musicpl
        else
            if [[ $current_musicpl = "nompd" ]]; then
                echo "mpd" > $current_musicpl
            fi
        fi
    ;;
esac
