#!/usr/bin/env bash

_wayland(){
    gammastep -l 0:0 -t 4000:4000 -r &> /dev/null &
}

_x11(){
    redshift -l 0:0 -t 4000:4000 -r &> /dev/null &
}

if [ $XDG_SESSION_TYPE == "wayland" ]; then
    _wayland
else
    _x11
fi


