#!/usr/bin/env bash
# Requires that you have allowed cpufreq-set to run without password.
if pgrep picom; then
    pkill picom
    sudo cpupower frequency-set -g performance
    echo "ON"
else
    picom --experimental-backends --config ~/.config/picom/picom.conf &
    sudo cpupower frequency-set -g powersave
    echo "OFF"
fi
