#!/usr/bin/env bash

DMENU="rofi -dmenu -i -p Action Center"
# OPTIONS = [[label, command]]
OPTIONS='''
[
  [ "Apps Menu",        "rofi_app_menu"],
  [ "Calculator",       "rofi_calc"],
  [ "Clipboard",        "env CM_HISTLENGTH=20 CM_LAUNCHER=rofi clipmenu"],
  [ "Cheatsheets",      "rofi_cheatsheets"],
  [ "Dotfiles",         "rofi_edit"],
  [ "Global Menu",      "rofi_global_menu"],
  [ "Kill",             "rofi_kill" ],
  [ "MPD",              "rofi_mpdmenu" ],
  [ "Network Manager",  "rofi_network_manager" ],
  [ "Password Manager", "rofi-pass"],
  [ "Record",           "rofi_record"],
  [ "Screenshot",       "shot"],
  [ "Switcher",         "rofi_switcher"],
  [ "Todo",             "rofi_todo"],
  [ "Translate",        "rofi_translate -i" ],
  [ "Youtube",          "rofi_youtube" ]
]
'''

label=$(echo $OPTIONS | jq -r "sort | .[][0]" | $DMENU)
exec $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$label\") | .[1]")
