#!/usr/bin/env bash

DMENU="rofi -dmenu -lines 3 -width 30 -i -p Record"
_XDG_=$(xdg-user-dir VIDEOS)/Recordings
OUTDIR="${_XDG_:-$HOME/Videos/Recordings}"
recordid="/tmp/recordid"

function audioVideo() {
    notify-send "Start Recording" "With:\nVideo On\nAudio On"

    filename="$OUTDIR/video-$(date '+%y%m%d-%H%M-%S').mkv"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -y -f x11grab -framerate 30 -s $dimensions \
        -i :0.0 -f alsa -i default \
        -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 \
        -c:a aac $filename &

    echo $! >$recordid
}

function video() {
    notify-send "Start Recording" "With:\nVideo On\nAudio Off"

    filename="$OUTDIR/video-$(date '+%y%m%d-%H%M-%S').mp4"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -y -f x11grab -framerate 30 -s $dimensions \
        -i :0.0 -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 \
        -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 $filename &

    echo $! >$recordid
}

function audio() {
    notify-send "Start Recording" "With:\nVideo Off\nAudio On"

    filename="$OUTDIR/audio-$(date '+%y%m%d-%H%M-%S').mp3"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -f alsa -i default -ac 2 -acodec libmp3lame -ab 128k $filename &

    echo $! >$recordid
}

function stoprecord() {
    if [ -f $recordid ]; then
        kill -15 $(cat $recordid)
        rm $recordid
    fi

    sleep 5
    if [ "$(pidof ffmpeg)" != "" ]; then
        pkill ffmpeg
    fi
}


function endrecord() {
    OPTIONS='["Yes", "No"]'
    select=$(echo $OPTIONS | jq -r ".[]" | $DMENU -mesg "Stop Recording")
    [ "$select" == "Yes" ] && stoprecord
}

function startrecord() {
    OPTIONS='''
    [
        ["難 Audio Video",        "audioVideo"],
        ["  Video Only",         "video"],
        ["  Audio Only",         "audio"]
    ]
    '''
    select=$(echo $OPTIONS | jq -r ".[][0]" | $DMENU)
    eval $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$select\") | .[1]")
}

if [ -f $recordid ]; then
    endrecord
else
    startrecord
fi
