#!/bin/bash
# dmenu_mpv
# Copyright (c) 2020 M. Nabil Adani <nblid48[at]gmail[dot]com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Resource:
# mpvc: https://github.com/lwilletts/mpvc

DMENU="rofi -dmenu -i"
DIR=${$(xdg-user-dir VIDEOS):-$HOME/Videos}

OPT=${1:-track}
case $OPT in
    track|"-t")
        track=$(mpvc -i | sed -r 's/\x1B\[(;?[0-9]{1,3})+[mGK]//g' | tr -d "\t" | \
                $DMENU -p "MPV Track" | cut -d " " -f 1)
        if [[ ! -z $track ]]; then
            mpvc -J $track
        fi
    ;;
    playlist|"-p")
        PLAYLIST_DIR=$HOME/.config/mpv/playlist
        PLAYLIST_FILE=$(ls $PLAYLIST_DIR | $DMENU -p "MPV Playlist" -l 10 )

        if [[ ! -z $PLAYLIST_FILE ]]; then
            mpv ${PLAYLIST_DIR}/${PLAYLIST_FILE}
        fi
    ;;
esac
