#!/usr/bin/env bash
# File              : dmenu_translate (rofi_translate)
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Last Modified By  : Atalazer <baraboyolali@gmail.com>

DMENU="rofi -dmenu -i -l 5"
ICON="$HOME/.config/awesome/icons/linebit/keyboard.png"

COUNTRY='''
[
  { "code": "id", "name": "Indonesian" },
  { "code": "en", "name": "English" },
  { "code": "jv", "name": "Javanese" },
  { "code": "ja", "name": "Japanese" },
  { "code": "ar", "name": "Arabic" }
]
'''

translateText() {
    text="$1"
    if [ -z "$text" ]; then
        exit
    fi
    name=$(echo $COUNTRY | jq -r ".[].name" | $DMENU -p "Translate ")
    if [ ! -z "$name" ]; then
        code=$(echo $COUNTRY | jq -r ".[] | select(.name == \"$name\") | .code")
        result=$(trans -b --download-audio-as /tmp/trans.ts :$code "$text")
        again=true

        # notify-send -i $ICON "Translate" "Result of '$text' in $name is '$result'"

        # notify-send -u low -i $ICON "Translate" "Result saved to clipboard"
        echo -n "$result" | xclip

        while $again; do
            menu=$(echo -e "Repeat\nPlay Audio\nExit" | $DMENU -lines 2 -p "Menu" -mesg "Result: $result")
            if [[ $menu == "Repeat" ]]; then
                text=$($DMENU -p "Translate")
                translateText "$text"
            elif [[ $menu == "Play Audio" ]]; then
                mpv /tmp/trans.ts
            else
                again=false
            fi
        done
    fi
}

case "$1" in
"-c" | "--clipboard")
    text=$(xclip -selection clipboard -o | tr --delete '\n')
    translateText "$text"
    ;;
"-i" | "--input")
    text=$($DMENU -p "Translate")
    translateText "$text"
    ;;
*)
    echo "Usage dmenu_translate [options]"
    echo ""
    echo "Available Options:"
    echo "-c  --clipboard   read text from clipboard"
    echo "-i  --input       read text from user input"
    echo ""
    ;;
esac
