#! /bin/sh

# Autostart
# =======================================
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &

# General
# ==============================
# bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5
bspc config focus_follows_pointer true

# Colors
# =============================
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# Border and Gaps
# =============================
bspc config border_width        2
bspc config borderless_monocle  false

bspc config window_gap          12
bspc config split_ratio         0.50
bspc config gapless_monocle     true

# Rules
# =============================
bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled split_ratio=0.6

# floating
rule_floating_center(){ bspc rule -a "$1" state=floating center=on; }
rule_floating_center Arandr
rule_floating_center GParted
rule_floating_center Gcolor3
rule_floating_center Nm-connection-editor
rule_floating_center scrcpy
rule_floating_center mpv

# workspace
rule_desktop (){ bspc rule -a "$2" desktop="^$1"; }
rule_desktop 1 kitty
rule_desktop 1 Alacritty
rule_desktop 2 firefox
rule_desktop 2 qutebrowser
rule_desktop 2 Brave-browser
rule_desktop 3 TelegramDesktop

