swipe:
    3:
        left:
            command: 'xdotool key alt+Right' # History forward
            keypress:
                LEFTSHIFT:
                    command:  'xdotool key shift+ctrl+Tab'
        right:
            command: 'xdotool key alt+Left' # History back
            keypress:
                LEFTSHIFT:
                    command:  'xdotool key ctrl+Tab'
        up:
            command: 'xdotool key ctrl+t' # Open new tab
            keypress:
                LEFTSHIFT:
                    command: 'xdotool key --clearmodifiers ctrl+shift+t' # Open last closed tab
        down:
            command: 'xdotool key ctrl+w' # Close tab
    4:
        left:
            command: 'xdotool key --clearmodifiers super+alt+Right'
        right:
            command: 'xdotool key --clearmodifiers super+alt+Left'
pinch:
    2:
        in:
            command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
        out:
            command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out

plugin:
    inputs:
        libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
            enable-tap: true # click to tap
            enable-dwt: true # disable tap while typing
            show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
