swipe:
  4:
    left:
      workspace: "next"
      keypress:
        LEFTSHIFT:
          window: "next"
    right:
      workspace: "prev"
      keypress:
        LEFTSHIFT:
          window: "prev"
    up:
      window:
        maximized: "add"
      keypress:
        LEFTSHIFT:
          window:
            fullscreen: "add"
    down:
      window:
        maximized: "remove"
      keypress:
        LEFTSHIFT:
          window:
            fullscreen: "remove"

---
context:
  application:  firefox
swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT"
      keypress:
        LEFTCTRL:
          sendkey: "LEFTCTRL+LEFTSHIFT+TAB"
    right:
      sendkey: "LEFTALT+LEFT"
      keypress:
        LEFTCTRL:
          sendkey: "LEFTCTRL+TAB"
    up:
      sendkey: "LEFTCTRL+T"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTCTRL+LEFTSHIFT+T"
    down:
      sendkey: "LEFTCTRL+W"
pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
---

---
context:
  application:  kitty
swipe:
  3:
    left:
      sendkey: "LEFTCTRL+LEFTSHIFT+RIGHTBRACE"
    right:
      sendkey: "LEFTCTRL+LEFTSHIFT+LEFTBRACE"
    # up:
    #   sendkey: "LEFTCTRL+LEFTSHIFT+T"
    # down:
    #   sendkey: "LEFTCTRL+LEFTSHIFT+W"
---

plugin:
  executors:
    wmctrl_executor:
      wrap-navigation: true
  inputs:
    libinput_command_input:   # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true        # click to tap
      enable-dwt: true        # disable tap while typing
show-keycodes: true     # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
