#!/usr/bin/env bash

up="pamixer -i 5"
down="pamixer -d 5"
mute="pamixer -t"
current_vol() { 
    amixer -D pulse get Master | grep '%' | head -n 1 | awk -F'[' '{print $2}' | awk -F'%' '{print $1}'; 
}


case $1 in
    up) 
        bash -c "$up"
        notify-send $(current_vol)
    ;;
    down) 
        bash -c "$down"
        notify-send $(current_vol)
    ;;
    mute) 
        bash -c "$mute"
        notify-send $(current_vol)
    ;;
    get) 
        current_vol
    ;;
esac

