#!/bin/sh

[ -f $HOME/.profile ] && source $HOME/.profile

# Lunch dbus-launch, this is important for some app
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# For several script and if using awesomeWM
export CHECK_AWESOME_CLIENT=true

# Initialization
xset -b                 # Disable terminal bell
xset r rate 300 50      # Set repeat rate

# Themes
theme-changer --toggle auto     # Change Theme based on Time
light -I                        # Restore Brightness
# wal -n -t -R                  # Restore wal

# Autostart Apps
/lib/mate-polkit/polkit-mate-authentication-agent-1 &>/dev/null &   # Polkit Agent
clipmenud &>/dev/null &                                             # Clipboard Manager
mpd &>/dev/null &                                                   # Music Player Daemon
# fcitx5 --replace -d &>/dev/null &                                 # Input Method for Japanese(mozc) and Arabic(m17n)
# an2linuxserver.py &>/dev/null &                                   # Send notification from android to linux
# fusuma -c ~/.config/fusuma/config.yml -d &>/dev/null &            # Libinput Touchpad Gestur
picom --config ~/.config/picom/picom.conf \
    --experimental-backends  --daemon &>/dev/null &

