#!/bin/sh
# vim: ft=sh ts=4 sw=4:

[ -f $HOME/.profile ] && . $HOME/.profile
[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile ] && . ${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile

# Lunch dbus-launch, this is important for some app
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# For several script and if using awesomeWM
export CHECK_AWESOME_CLIENT=true

# Initialization
xset -b                 # Disable terminal bell
xset r rate 300 50      # Set repeat rate

# Themes
theme-changer --toggle auto     # Change Theme based on Time
light -I                        # Restore Brightness
# wal -n -t -R                  # Restore wal

# Autostart Apps
/lib/mate-polkit/polkit-mate-authentication-agent-1 >/dev/null 2>&1 &   # Polkit Agent
clipmenud >/dev/null 2>&1 &                                             # Clipboard Manager
mpd >/dev/null 2>&1 &                                                   # Music Player Daemon
# fcitx5 --replace -d >/dev/null 2>&1 &                                 # Input Method for Japanese(mozc) and Arabic(m17n)
# an2linuxserver.py >/dev/null 2>&1 &                                   # Send notification from android to linux
# fusuma -c ~/.config/fusuma/config.yml -d >/dev/null 2>&1 &            # Libinput Touchpad Gestur
picom --config ~/.config/picom/picom.conf \
    --experimental-backends  --daemon >/dev/null 2>&1 &

