name: emoji
parent: default

matches:
  - triggers: [":indonesia:", ":id:"]
    replace: "\U0001F1EE\U0001F1E9"

  - triggers: [":lol:", ":laugh:"]
    replace: "\U0001F602"

  - trigger: ':deal:'
    replace: "\U0001F91D"

  - triggers: [':pray:',':please:',':hope:',':wish:']
    replace: "\U0001F64F"

  - triggers: [":approve:", ":+1:", ":tumbup:"]
    replace: "\U0001F91D"

  - triggers: [ ":disapprove:", ":bury:", ":-1:", ":tumbdown:"]
    replace: "\U0001F44E"

