#!/bin/sh

export FORGIT_FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --height '100%'"
export FORGIT_PAGER=$PAGER
export FORGIT_SHOW_PAGER=$FORGIT_PAGER
export FORGIT_IGNORE_PAGER="bat -l gitignore --color always"
FORGIT_DIFF_PAGER="$(git config pager.diff || echo 'delta --diff-so-fancy --line-numbers')"
export FORGIT_DIFF_PAGER

export forgit_log=glg
export forgit_diff=gd
export forgit_add=ga
export forgit_reset_head=grh
export forgit_ignore=gi
export forgit_checkout_file=gcf
export forgit_checkout_branch=gcb
export forgit_checkout_commit=gco
export forgit_clean=gclean
export forgit_stash_show=gss
export forgit_cherry_pick=gcp
export forgit_rebase=grb
export forgit_fixup=gfu
