lastupdatecheck: 0
recentrepos:
- /home/atalariq/.dotfiles
- /home/atalariq/Documents/Notes
- /home/atalariq/Applications/build/zk
- /home/atalariq/Applications/python/wisdom-tree
- /home/atalariq/Documents/Programming/Repo/wally.nvim
- /home/atalariq/Documents/Programming/Repo/xresources-nvim
- /home/atalariq/Applications/build/nnn
- /home/atalariq/Backups/Config/awesome/awesome-glorious-widgets
- /home/atalariq/Applications/build/lule
- /home/atalariq/Backups/Dotfiles/mnabila-dotfiles
- /home/atalariq/Documents/Programming/Dev/conflict
- /home/atalariq/Documents/Blog/atalazer.github.io-dev
- /home/atalariq/Documents/Programming/eBook/Bash-Bible
startuppopupversion: 5
