#!/bin/sh

[ -f ~/.user.keys ] && . ~/.user.keys

CHARSET=UTF-8; LANG=en_US.UTF-8
export MM_CHARSET=$CHARSET; export LANG=$LANG; export LC_ALL=$LANG
export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive

## Apps
export TERMINAL="kitty"
export BROWSER="qutebrowser"
export FILEMAN="thunar"

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"

# CMD
export PERMISSION="sudo"
export SHUTDOWN_CMD="poweroff"
export REBOOT_CMD="reboot"
export SUSPEND_CMD="suspend"
export LOCK_CMD=""

export TRASH_CMD="gio"

# Dirs
export APP_DIR="$HOME/Applications"
export BIN_DIR="$HOME/.local/bin"
export BACKUP_DIR="$HOME/Backups"
export NOTE_DIR="$HOME/Documents/Notes"
export SCHOOL_DIR="$HOME/Documents/School"
export PROGRAMMING_DIR="$HOME/Documents/Project"
export REPO_DIR="$HOME/Documents/GitHub"

export BLOG="$HOME/Documents/Blog"
export DOTS="$HOME/.dotfiles"

# Misc
export WAL_BACKEND=colorthief       # wal colorthief

