#!/bin/sh

[ -f "$HOME/.user.keys" ] && source "$HOME/.user.keys"

# Dirs
export APP_DIR="$HOME/Applications"
export BIN_DIR="$HOME/.local/bin"
export BACKUP_DIR="$HOME/Backups"
export NOTE_DIR="$HOME/Documents/Notes"
export SCHOOL_DIR="$HOME/Documents/School"
export PROGRAMMING_DIR="$HOME/Documents/Programming/Project"
export REPO_DIR="$HOME/Documents/Programming/Repo"

export BLOG="$HOME/Documents/Blog"
export DOTS="$HOME/.dotfiles"

# Misc
export WAL_BACKEND=colorthief       # wal colorthief

