#! /bin/sh

# Autostart
# =======================================
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &

# General
# ==============================
# bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5
bspc config focus_follows_pointer true

# Colors
# =============================
# source the colors.
source "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# Border and Gaps
# =============================
bspc config border_width         2
bspc config borderless_monocle   false

bspc config window_gap          12
bspc config split_ratio          0.50
bspc config gapless_monocle      true

# Rules
# =============================
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
