require("indent_blankline").setup({
    use_treesitter = true,
    show_foldtext = true,
    show_end_of_line = false,
    show_trailing_blankline_indent = false,
    show_current_context = true,
    show_first_indent_level = true,
    indent_level = 10,
    char = "│",
    space_char_blankline = " ",
    context_patterns = {
        "class",
        "function",
        "method",
        "block",
        "list_literal",
        "selector",
        "^if",
        "^table",
        "if_statement",
        "while",
        "for",
    },
    buftype_exclude = {
        "terminal",
        "prompt",
        "nofile",
    },
    filetype_exclude = {
        "help",
        "markdown",
        "text",
        "Nvimtree",
        "Outline",
        "Trouble",
        "packer",
        "dashboard",
    },
})
