gui:
  scrollHeight: 3 # how many lines you scroll by
  sidePanelWidth: 0.35 # number from 0 to 1
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
notARepository: "skip" # one of: "prompt" | "create" | "skip"
git:
  paging:
    colorArg: always
    pager: "delta"
    useConfig: false
os:
  editCommand: "$EDITOR" # see "Configuring File Editing" section
  openCommand: "sh -c 'opener {{filename}} >/dev/null'"
