lastupdatecheck: 0
recentrepos:
- /home/atalariq/Backups/Dotfiles/mnabila-dotfiles
- /home/atalariq/Documents/Programming/Dev/conflict
- /home/atalariq/Documents/Blog/atalazer.github.io-dev
- /home/atalariq/.dotfiles
- /home/atalariq/Applications/build/nnn
- /home/atalariq/Documents/Programming/eBook/Bash-Bible
startuppopupversion: 5
